org: paulbtw
app: mcbrokenio
service: mcbrokenio
variablesResolutionMode: 20210326
useDotenv: true

frameworkVersion: '2'

package:
  excludeDevDependencies: true

plugins:
  - serverless-plugin-typescript
  - serverless-plugin-log-subscription

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: ${opt:region, 'eu-central-1'}
  stage: ${opt:stage, 'dev'}
  deploymentBucket:
    name: mcbrokenio-paulbtw
  tags:
    project: mcbrokenio
    owner: paulbtw
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:GetParameters
      Resource: '*'
    - Effect: Allow
      Action:
        - secretmanager:GetSecretValue
      Resource:
        - 'arn:aws:secretsmanager:eu-central-1:*:secret:*'
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:GetObjectVersion
      Resource:
        - arn:aws:s3:::*

custom:
  mcdInfo:
    basicTokenEU: ${ssm:/mcdonalds/eu/basictoken}
    mcdUsername: ${ssm:/mcdonalds/eu/username}
    mcdPassword: ${ssm:/mcdonalds/eu/password}
    mcdDeviceId: ${ssm:/mcdonalds/eu/deviceId}
    databaseUrl: ${ssm:/mcdonalds/database}
    exportBucket: ${ssm:/mcdonalds/export/bucket}
    mcdElKey: ${ssm:/mcdonalds/el/key}
    basicTokenEL: ${ssm:/mcdonalds/el/basictoken}

functions:
  getIceMaschineStatus:
    handler: src/functions/getIceMaschineStatus/handler.main
    memorySize: 512
    timeout: 600
    environment:
      BASIC_TOKEN_EU: ${self:custom.mcdInfo.basicTokenEU}
      BASIC_TOKEN_EL: ${self:custom.mcdInfo.basicTokenEL}
      DATABASE_URL: ${self:custom.mcdInfo.databaseUrl}
      MCD_USERNAME: ${self:custom.mcdInfo.mcdUsername}
      MCD_PASSWORD: ${self:custom.mcdInfo.mcdPassword}
      MCD_DEVICEID: ${self:custom.mcdInfo.mcdDeviceId}
    events:
      - schedule:
          rate: rate(5 minutes)
  getAllStores:
    handler: src/functions/getAllStores/handler.main
    memorySize: 512
    timeout: 900
    environment:
      BASIC_TOKEN: ${self:custom.mcdInfo.basicTokenEU}
      DATABASE_URL: ${self:custom.mcdInfo.databaseUrl}
      KEY: ${self:custom.mcdInfo.mcdElKey}
    events:
      - schedule: cron(30 8 * * ? *)
  createJson:
    handler: src/functions/createJson/handler.main
    memorySize: 512
    timeout: 60
    environment:
      BUCKET: ${self:custom.mcdInfo.exportBucket}
      DATABASE_URL: ${self:custom.mcdInfo.databaseUrl}
    events:
      - schedule:
          rate: rate(30 minutes)
