import { Logger } from '@sailplane/logger';
import axios from 'axios';

const logger = new Logger('makeTestOrder');

/**
 * Currently not working...
 * You can place an order even if the Store has a broken machine.
 * Need to look into this, maybe you need to add it to the cart first to receive an error.
 */
export const makeTestOrder = async (
  bearerToken: string,
  clientId: string,
  storeId: number,
) => {
  try {
    const orderResponse = await axios.post(
      'https://eu-prod.api.mcd.com/exp/v1/order',
      {
        orderView: {
          products: [
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 4237,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 4256,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 4258,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 4255,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 4252,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 4603,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [
                {
                  quantity: 1,
                  isAutoEVM: false,
                  productCode: 10000082,
                  choiceSolution: {
                    quantity: 1,
                    isAutoEVM: false,
                    productCode: 4313,
                    deliverEarlyQuantity: 0,
                    isFee: false,
                    choices: [],
                    components: [],
                    customizations: [],
                    promoQuantity: 0,
                  },
                  deliverEarlyQuantity: 0,
                  isFee: false,
                  choices: [],
                  components: [],
                  customizations: [],
                  promoQuantity: 0,
                },
              ],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 4604,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [
                {
                  quantity: 1,
                  isAutoEVM: false,
                  productCode: 10000082,
                  choiceSolution: {
                    quantity: 1,
                    isAutoEVM: false,
                    productCode: 4313,
                    deliverEarlyQuantity: 0,
                    isFee: false,
                    choices: [],
                    components: [],
                    customizations: [],
                    promoQuantity: 0,
                  },
                  deliverEarlyQuantity: 0,
                  isFee: false,
                  choices: [],
                  components: [],
                  customizations: [],
                  promoQuantity: 0,
                },
              ],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 4651,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [
                {
                  quantity: 1,
                  isAutoEVM: false,
                  productCode: 10000082,
                  choiceSolution: {
                    quantity: 1,
                    isAutoEVM: false,
                    productCode: 4313,
                    deliverEarlyQuantity: 0,
                    isFee: false,
                    choices: [],
                    components: [],
                    customizations: [],
                    promoQuantity: 0,
                  },
                  deliverEarlyQuantity: 0,
                  isFee: false,
                  choices: [],
                  components: [],
                  customizations: [],
                  promoQuantity: 0,
                },
              ],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 5010,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [
                {
                  quantity: 1,
                  isAutoEVM: false,
                  productCode: 10000081,
                  choiceSolution: {
                    quantity: 1,
                    isAutoEVM: false,
                    productCode: 4314,
                    deliverEarlyQuantity: 0,
                    isFee: false,
                    choices: [],
                    components: [],
                    customizations: [],
                    promoQuantity: 0,
                  },
                  deliverEarlyQuantity: 0,
                  isFee: false,
                  choices: [],
                  components: [],
                  customizations: [],
                  promoQuantity: 0,
                },
              ],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 5000,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [
                {
                  quantity: 1,
                  isAutoEVM: false,
                  productCode: 10000081,
                  choiceSolution: {
                    quantity: 1,
                    isAutoEVM: false,
                    productCode: 4314,
                    deliverEarlyQuantity: 0,
                    isFee: false,
                    choices: [],
                    components: [],
                    customizations: [],
                    promoQuantity: 0,
                  },
                  deliverEarlyQuantity: 0,
                  isFee: false,
                  choices: [],
                  components: [],
                  customizations: [],
                  promoQuantity: 0,
                },
              ],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
            {
              quantity: 1,
              isAutoEVM: false,
              productCode: 5020,
              deliverEarlyQuantity: 0,
              isFee: false,
              choices: [
                {
                  quantity: 1,
                  isAutoEVM: false,
                  productCode: 10000081,
                  choiceSolution: {
                    quantity: 1,
                    isAutoEVM: false,
                    productCode: 4314,
                    deliverEarlyQuantity: 0,
                    isFee: false,
                    choices: [],
                    components: [],
                    customizations: [],
                    promoQuantity: 0,
                  },
                  deliverEarlyQuantity: 0,
                  isFee: false,
                  choices: [],
                  components: [],
                  customizations: [],
                  promoQuantity: 0,
                },
              ],
              components: [],
              customizations: [],
              promoQuantity: 0,
            },
          ],
          promotionListView: [],
          payment: {
            paymentMethodId: 4,
            paymentDataId: -1,
            pod: 0,
            customerPaymentMethodId: 0,
          },
          priceType: 1,
          fulfillmentType: 1,
          storeId: `${storeId}`,
          prepareFood: 0,
        },
      },
      {
        headers: {
          authorization: `Bearer ${bearerToken}`,
          'mcd-clientId': clientId,
          'mcd-uuid': '2BCEEEC5-E3DC-4F8E-9832-A03C277DE009',
          'accept-language': 'de-DE',
          'mcd-marketid': 'DE',
        },
      },
    );

    if (orderResponse.status === 200) {
      return true;
    }
  } catch (error) {
    logger.debugObject('Error: ', error);
  }
  return false;
};
