export enum IceType {
  MCFLURRY = 'MCFLURRY',
  MCSUNDAE = 'MCSUNDAE',
  MILCHSHAKE = 'MILCHSHAKE',
}

export enum ItemStatus {
  'AVAILABLE' = 'AVAILABLE',
  'PARTIAL_AVAILABLE' = 'PARTIAL_AVAILABLE',
  'UNAVAILABLE' = 'UNAVAILABLE',
  'NOT_APPLICABLE' = 'NOT_APPLICABLE',
  'UNKNOWN' = 'UNKNOWN'
}
