name: Deployment-Database(migration)

on:
  push:
    branches:
      - master

jobs:
  migration:
    name: Run migrations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '14.18.1'
      - run: yarn install
      - name: migrations
        run: yarn typeorm -f src/ormconfig.ts migration:run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
