name: Deployment-Serverless(AWS)

on:
  push:
    branches:
      - master

jobs:
  deployment-aws:
    name: Deploy AWS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Serverless Framework
        run: npm install -g serverless@2.67.0
      - run: yarn install
      - name: migrations
        run: yarn typeorm -f src/ormconfig.ts migration:run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Serverless AWS deployment
        run: sls deploy
        env:
          BASIC_TOKEN_AP: ${{ secrets.BASIC_TOKEN_AP }}
          BASIC_TOKEN_EU: ${{ secrets.BASIC_TOKEN_EU }}
          BASIC_TOKEN_EL: ${{ secrets.BASIC_TOKEN_EL }}
          BASIC_TOKEN_US: ${{ secrets.BASIC_TOKEN_US }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MCD_DEVICEID: ${{ secrets.MCD_DEVICEID }}
          KEY: ${{ secrets.KEY }}
          API_KEY_AP: ${{ secrets.API_KEY_AP }}
