name: Deployment-Database(migration)

on:
  push:
    branches:
      - master

jobs:
  migration:
    name: Run migrations
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: migrations
        run: yarn typeorm -f src/ormconfig.ts migration:run
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
